# Generated by Django 5.1.2 on 2024-10-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category_alter_product_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsuppliers',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
