# Generated by Django 5.1.2 on 2024-10-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsuppliers',
            old_name='quantity',
            new_name='supply',
        ),
    ]
